codecov:
  notify:
    require_ci_to_pass: yes

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

# don't gather statistics for tets and external libraries
ignore:
  - tests/.*
  - zip/.*
  - 3rdParty/.*
