image: Visual Studio 2013

matrix:
  fast_finish: true

platform:
  - Win32
#  - x64

configuration:
  - Debug
#  - Release

environment:
  matrix:
    - TOOLCHAIN_VERSION: 12.0
      solution_name: win_build\boinc_vs2013.sln
      depends_git_path: http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git
      depends_path: C:\projects\boinc_depends_win_vs2013
    - TOOLCHAIN_VERSION: 12.0
      solution_name: win_build\boinc_vs2013_ibm.sln
      depends_git_path: http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git
      depends_path: C:\projects\boinc_depends_win_vs2013

before_build:
  - git clone -q --branch=master %depends_git_path% %depends_path%
  - if %TOOLCHAIN_VERSION%==12.0 call "%VS120COMNTOOLS%\vsvars32.bat"

build_script:
  - devenv %solution_name% /Build

build:
  parallel: true

test: off
